name: Match Pulumi state
run-name: Running 'pulumi up' to update Azure with new components
on: [push]

jobs:
  pulumi-up:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: pulumi/actions@v7
        with:
          command: preview
          stack-name: azurek8s
          cloud-url: azblob://paulscoolpulumicontainer?storage_account=paulscoolpulumistorage
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}